name: Package

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: package-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  arch:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/arch-package.yml@cda4f4fa38fc8142439665f0e2d1946bc37ac595
    with:
      extra-repos: |
        [mason]
        SigLevel = Required DatabaseRequired
        Server = https://masonrhodesdev.github.io/arch-repo/x86_64
      extra-repo-key-url: https://masonrhodesdev.github.io/arch-repo/mason-repo.asc
      extra-repo-key-fingerprint: 41450EEF8CEE7AB8CD3896221284404A6B70485C
  rpm:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/rpm-check.yml@cda4f4fa38fc8142439665f0e2d1946bc37ac595
    with:
      spec-name: hypr-de
