name: Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    uses: MasonRhodesDev/packaging-workflows/.github/workflows/release.yml@8eaac4277eccc554e0a02043dbe8a083830b04ee
    secrets: inherit
    with:
      spec-name: hypr-de
      copr-project: hypr-de
      extra-repos: |
        [mason]
        SigLevel = Required DatabaseRequired
        Server = https://masonrhodesdev.github.io/arch-repo/x86_64
      extra-repo-key-url: https://masonrhodesdev.github.io/arch-repo/mason-repo.asc
      extra-repo-key-fingerprint: 41450EEF8CEE7AB8CD3896221284404A6B70485C
